CREATE SEQUENCE IF NOT EXISTS authors_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS books_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE authors
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(128)                            NOT NULL,
    biography VARCHAR(128),
    CONSTRAINT authors_pk PRIMARY KEY (id)
);

CREATE TABLE book_authors
(
    book_id   BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    id        BIGINT NOT NULL,
    CONSTRAINT book_authors_pk PRIMARY KEY (id)
);

CREATE TABLE books
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(128)                            NOT NULL,
    description  VARCHAR(128),
    view_counter BIGINT                                  NOT NULL,
    date_added   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT books_pk PRIMARY KEY (id)
);

ALTER TABLE book_authors
    ADD CONSTRAINT book_authors_authors_fk FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE NO ACTION;

ALTER TABLE book_authors
    ADD CONSTRAINT book_authors_books_fk FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE NO ACTION;